/*
 * Copyright (c) 2026 The Regents of the University of California
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "pickle/application_specific/prefetcher/prefetch_generators/cg.hh"

#include "base/logging.hh"
#include "base/trace.hh"
#include "debug/PickleDevicePrefetcherTrace.hh"
#include "debug/PickleDevicePrefetcherWorkTrackerDebug.hh"
#include "mem/packet.hh"
#include "pickle/application_specific/prefetcher/pickle_prefetcher.hh"
#include "pickle/application_specific/prefetcher/prefetcher_work_tracker.hh"

namespace gem5
{

CGSpMVPrefetchGenerator::CGSpMVPrefetchGenerator(
    std::string _name,
    const uint64_t _job_id, const uint64_t _core_id,
    const uint64_t _software_hint_distance,
    const uint64_t _prefetch_distance_offset_from_software_hint,
    PrefetcherWorkTracker* _work_tracker
) : PrefetchGenerator(
    _name,
    _job_id, _core_id,
    _software_hint_distance, _prefetch_distance_offset_from_software_hint,
    _work_tracker
    )
{
}

// The below code is generated by Claude Opus 4.6
std::shared_ptr<WorkItem>
CGSpMVPrefetchGenerator::execute_kernel(Addr work_data)
{
    // ================================================================
    // CG SpMV Prefetch Generator
    //
    // Application code (cg.f90, conj_grad subroutine):
    //
    //   do j = 1, lastrow-firstrow+1
    //       pkl_row_hint = int(j - 1, c_int64_t)       ! 0-based
    //       call pickle_cg_spmv_hint_c(pkl_kid, pkl_row_hint)
    //       suml = 0.d0
    //       do k = rowstr(j), rowstr(j+1)-1
    //           suml = suml + a(k) * p(colidx(k))
    //       enddo
    //       q(j) = suml
    //   enddo
    //
    // Array descriptors (from pickle_cg_hooks.cpp):
    //   Array 0: rowstr  — CSR row pointers
    //       vaddr_start  = &rowstr(1)
    //       element_size = kz bytes (4 for class S-C, 8 for class D-F)
    //       Values: 1-based Fortran integer positions (NOT pointers)
    //
    //   Array 1: colidx  — CSR column indices
    //       vaddr_start  = &colidx(1) - 4   (1-based adjustment)
    //       element_size = 4
    //       Values: 1-based column indices into target vector
    //
    //   Array 2: p_vec or z_vec  — dense target vector
    //       vaddr_start  = &vec(1) - 8   (1-based adjustment)
    //       element_size = 8 (double precision)
    //
    // Hint:  work_data = 0-based row index (j - 1)
    //
    // Key difference from graph workloads:
    //   Graph out_index stores virtual-address pointers.
    //   CG rowstr stores integer positions (1-based).
    //   The generator must convert positions to addresses:
    //       colidx_vaddr = colidx.vaddr_start + position * colidx_esz
    //   This works because colidx.vaddr_start is shifted back by one
    //   element, making 1-based positions produce correct addresses.
    // ================================================================

    // Compute the future row to prefetch for
    const uint64_t row_0based = work_data \
        + software_hint_distance - prefetch_distance_offset_from_software_hint;

    // Bounds check: nrows = rowstr.num_elements - 1
    const uint64_t num_rows = \
        work_tracker->job_descriptor->get_array(0).num_elements() - 1;

    DPRINTF(
        PickleDevicePrefetcherTrace,
        "Received work_data: 0x%llx, row_0based: %lld, num_rows: %lld\n",
        work_data, row_0based, num_rows
    );

    if (row_0based >= num_rows) {
        return nullptr;
    }

    std::shared_ptr<WorkItem> workItem(new WorkItem(row_0based));

    constexpr Addr BLOCK_SHIFT = 6;

    // Array metadata
    const Addr rowstr_base = \
        work_tracker->job_descriptor->get_array(0).vaddr_start;
    const uint64_t rowstr_esz = \
        work_tracker->job_descriptor->get_array(0).element_size;
    const Addr colidx_base = \
        work_tracker->job_descriptor->get_array(1).vaddr_start;
    const uint64_t colidx_esz = \
        work_tracker->job_descriptor->get_array(1).element_size;
    assert(colidx_esz == 4);
    const Addr vec_base = \
        work_tracker->job_descriptor->get_array(2).vaddr_start;
    const uint64_t vec_esz = \
        work_tracker->job_descriptor->get_array(2).element_size;
    assert(vec_esz == 8);

    // 1-based positions read from rowstr
    uint64_t rowstr_start_pos = 0;   // rowstr(j)    = start of nonzeros
    uint64_t rowstr_end_pos = 0;     // rowstr(j+1)  = exclusive end
    std::vector<uint64_t> lv2_col_indices;

    // ================================================================
    // Level 1: Read rowstr[future_row] and rowstr[future_row + 1]
    //
    // rowstr.vaddr_start = &rowstr(1).
    // For 0-based index row_0based, rowstr(j) where j = row_0based + 1
    // is at vaddr_start + row_0based * rowstr_esz.
    //
    // The values read are 1-BASED Fortran integer positions into the
    // colidx/a arrays, NOT virtual-address pointers.
    // ================================================================
    // Read rowstr[future_row] (start position)
    {
        bool success = false;
        const Addr start_vaddr = rowstr_base + row_0based * rowstr_esz;
        const Addr start_vaddr_aligned = \
            (start_vaddr >> BLOCK_SHIFT) << BLOCK_SHIFT;
        DPRINTF(
            PickleDevicePrefetcherWorkTrackerDebug,
            "Fetching lv1 rowstr start vaddr 0x%llx\n",
            start_vaddr_aligned
        );
        PacketPtr pkt = \
            work_tracker->owner->zeroCycleLoadWithVAddr(
                start_vaddr_aligned, success
            );
        if (!success) {
            DPRINTF(
                PickleDevicePrefetcherTrace,
                "Failed to fetch level = 1, row = %lld, "
                "pf_vaddr = 0x%llx, start\n",
                row_0based, start_vaddr_aligned
            );
            return nullptr;
        }
        // Extract the value based on rowstr element size (kz = 4 or 8)
        if (rowstr_esz == 4) {
            const Addr offset = \
                (start_vaddr - start_vaddr_aligned) / 4;
            rowstr_start_pos = \
                (uint64_t)(pkt->getConstPtr<uint32_t>()[offset]);
        } else {
            const Addr offset = \
                (start_vaddr - start_vaddr_aligned) / 8;
            rowstr_start_pos = \
                (uint64_t)(pkt->getConstPtr<uint64_t>()[offset]);
        }
        workItem->addExpectedPrefetch(start_vaddr_aligned, 0);
        warnIfOutsideRanges(row_0based, start_vaddr_aligned);
        DPRINTF(
            PickleDevicePrefetcherTrace,
            "Row = %lld, rowstr_start_pos = %lld (1-based)\n",
            row_0based, rowstr_start_pos
        );
    }
    // Read rowstr[future_row + 1] (end position, exclusive)
    {
        bool success = false;
        const Addr end_vaddr = rowstr_base + (row_0based + 1) * rowstr_esz;
        const Addr end_vaddr_aligned = \
            (end_vaddr >> BLOCK_SHIFT) << BLOCK_SHIFT;
        DPRINTF(
            PickleDevicePrefetcherWorkTrackerDebug,
            "Fetching lv1 rowstr end vaddr 0x%llx\n",
            end_vaddr_aligned
        );
        PacketPtr pkt = \
            work_tracker->owner->zeroCycleLoadWithVAddr(
                end_vaddr_aligned, success
            );
        if (!success) {
            DPRINTF(
                PickleDevicePrefetcherTrace,
                "Failed to fetch level = 1, row = %lld, "
                "pf_vaddr = 0x%llx, end\n",
                row_0based, end_vaddr_aligned
            );
            return nullptr;
        }
        if (rowstr_esz == 4) {
            const Addr offset = \
                (end_vaddr - end_vaddr_aligned) / 4;
            rowstr_end_pos = \
                (uint64_t)(pkt->getConstPtr<uint32_t>()[offset]);
        } else {
            const Addr offset = \
                (end_vaddr - end_vaddr_aligned) / 8;
            rowstr_end_pos = \
                (uint64_t)(pkt->getConstPtr<uint64_t>()[offset]);
        }
        workItem->addExpectedPrefetch(end_vaddr_aligned, 0);
        warnIfOutsideRanges(row_0based, end_vaddr_aligned);
        DPRINTF(
            PickleDevicePrefetcherTrace,
            "Row = %lld, rowstr_end_pos = %lld (1-based, exclusive)\n",
            row_0based, rowstr_end_pos
        );
    }

    // ================================================================
    // Level 2: Read column indices from colidx
    //
    // Iterate over colidx positions [rowstr_start_pos, rowstr_end_pos).
    // These positions are 1-based Fortran indices.
    //
    // colidx.vaddr_start = &colidx(1) - colidx_esz  ("virtual element 0")
    // So  colidx.vaddr_start + pos * colidx_esz  gives the correct
    // virtual address for 1-based position pos.
    //
    // The values read from colidx are 1-based column indices into the
    // target vector (p or z).
    // ================================================================
    {
        Addr curr_block_vaddr = 1;  // sentinel: force first fetch
        PacketPtr pkt = nullptr;
        uint32_t* data_ptr = nullptr;
        lv2_col_indices.reserve(rowstr_end_pos - rowstr_start_pos);
        for (
            uint64_t pos = rowstr_start_pos;
            pos < rowstr_end_pos;
            pos++
        )
        {
            const Addr colidx_vaddr = colidx_base + pos * colidx_esz;
            const Addr colidx_vaddr_aligned = \
                (colidx_vaddr >> BLOCK_SHIFT) << BLOCK_SHIFT;
            if (colidx_vaddr_aligned != curr_block_vaddr) {
                bool success = false;
                DPRINTF(
                    PickleDevicePrefetcherWorkTrackerDebug,
                    "Fetching lv2 colidx vaddr 0x%llx\n",
                    colidx_vaddr_aligned
                );
                pkt = work_tracker->owner->zeroCycleLoadWithVAddr(
                    colidx_vaddr_aligned, success
                );
                if (!success) {
                    DPRINTF(
                        PickleDevicePrefetcherTrace,
                        "Failed to fetch level = 2, row = %lld, "
                        "vaddr = 0x%llx\n",
                        row_0based, colidx_vaddr_aligned
                    );
                    return nullptr;
                }
                curr_block_vaddr = colidx_vaddr_aligned;
                data_ptr = pkt->getPtr<uint32_t>();
                // Prefetch the colidx cache line itself
                workItem->addExpectedPrefetch(curr_block_vaddr, 1);
                warnIfOutsideRanges(row_0based, curr_block_vaddr);
            }
            const Addr local_offset = \
                (colidx_vaddr - curr_block_vaddr) / colidx_esz;
            lv2_col_indices.push_back(data_ptr[local_offset]);
            DPRINTF(
                PickleDevicePrefetcherTrace,
                "Row = %lld, colidx[%lld] = %lld (1-based col)\n",
                row_0based, pos, lv2_col_indices.back()
            );
        }
    }

    // ================================================================
    // Level 3: Prefetch target vector entries  vec[ col_idx ]
    //
    // vec.vaddr_start = &vec(1) - vec_esz   ("virtual element 0")
    // So  vec.vaddr_start + col_idx * vec_esz  gives the correct
    // virtual address for 1-based column index col_idx.
    //
    // This is the indirect access that causes cache misses for large
    // problem sizes.  The target vector (p or z, depending on which
    // SpMV kernel) is accessed at scattered positions determined by
    // the sparse matrix structure.
    // ================================================================
    {
        for (auto col_idx : lv2_col_indices) {
            const Addr vec_vaddr = vec_base + col_idx * vec_esz;
            const Addr vec_vaddr_aligned = \
                (vec_vaddr >> BLOCK_SHIFT) << BLOCK_SHIFT;
            workItem->addExpectedPrefetch(vec_vaddr_aligned, 2);
            warnIfOutsideRanges(row_0based, vec_vaddr_aligned);
            DPRINTF(
                PickleDevicePrefetcherTrace,
                "Row = %lld, vec prefetch = 0x%llx (col = %lld)\n",
                row_0based, vec_vaddr_aligned, col_idx
            );
        }
    }

    return workItem;
}


} // namespace gem5
