/*
 * Copyright (c) 2026 The Regents of the University of California
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "pickle/application_specific/prefetcher/prefetch_generators/is.hh"

#include "base/logging.hh"
#include "base/trace.hh"
#include "debug/PickleDevicePrefetcherTrace.hh"
#include "debug/PickleDevicePrefetcherWorkTrackerDebug.hh"
#include "mem/packet.hh"
#include "pickle/application_specific/prefetcher/pickle_prefetcher.hh"
#include "pickle/application_specific/prefetcher/prefetcher_work_tracker.hh"

namespace gem5
{

ISRankingPrefetchGenerator::ISRankingPrefetchGenerator(
    std::string _name,
    const uint64_t _job_id, const uint64_t _core_id,
    const uint64_t _software_hint_distance,
    const uint64_t _prefetch_distance_offset_from_software_hint,
    PrefetcherWorkTracker* _work_tracker
) : PrefetchGenerator(
    _name,
    _job_id, _core_id,
    _software_hint_distance, _prefetch_distance_offset_from_software_hint,
    _work_tracker
    )
{
}

// The below code is mostly generated by Claude Opus 4.6
std::shared_ptr<WorkItem>
ISRankingPrefetchGenerator::execute_kernel(Addr work_data)
{
    // ================================================================
    // IS Ranking Kernel Prefetch Generator
    //
    // Application code (is2.c, rank() function):
    //
    //     for (k = m; k < bucket_ptrs[i]; k++) {
    //         if (k + prefetch_distance < bucket_ptrs[i])
    //             *UCPage = (uint64_t)(&key_buff_ptr2[k]);
    //         key_buff_ptr[key_buff_ptr2[k]]++;
    //     }
    //
    // Array descriptors sent by the application:
    //     Array 0: key_buff2   (source array, iterated sequentially)
    //     Array 1: key_buff1   (target array, indexed by values from array 0)
    //
    // Access chain:  key_buff2 -> key_buff1
    //
    // The software hint (work_data) is the ADDRESS of key_buff2[k]
    // (the element the core is currently processing).
    //
    // This is simpler than graph workloads because there is no CSR
    // row-pointer indirection — it is a flat 2-level gather:
    //   Level 1: read key_buff2[k_future] to obtain the key value
    //   Level 2: prefetch key_buff1[key_value]
    // ================================================================

    // Array 0: key_buff2  (source, sequential iteration)
    // Array 1: key_buff1  (target, indirect access via key values)

    const uint64_t key_buff2_element_size =
        work_tracker->job_descriptor->get_array(0).element_size;
    const uint64_t key_buff1_element_size =
        work_tracker->job_descriptor->get_array(1).element_size;

    // Compute the address of the future element in key_buff2.
    // work_data = &key_buff2[k], and we want &key_buff2[k + distance].
    const Addr element_id =
        work_data
        + software_hint_distance
        - prefetch_distance_offset_from_software_hint;

    std::shared_ptr<WorkItem> workItem(new WorkItem(element_id));

    const Addr key_buff2_base =
        work_tracker->job_descriptor->get_array(0).vaddr_start;
    const Addr work_vaddr =
        key_buff2_base + element_id * key_buff2_element_size;

    constexpr Addr BLOCK_SHIFT = 6;
    uint64_t lv1_key_value = 0;

    // Level 1: read the future key value from key_buff2
    //
    // We fetch the cache line containing key_buff2[k_future] and extract
    // the key value. This value will be used as an index into key_buff1.
    {
        bool success = false;
        const Addr block_aligned_vaddr = \
            (work_vaddr >> BLOCK_SHIFT) << BLOCK_SHIFT;
        DPRINTF(
            PickleDevicePrefetcherWorkTrackerDebug,
            "Fetching lv1 (key_buff2) vaddr 0x%llx\n",
            block_aligned_vaddr
        );
        PacketPtr pkt = \
            work_tracker->owner->zeroCycleLoadWithVAddr(
                block_aligned_vaddr, success
            );
        if (!success) {
            DPRINTF(
                PickleDevicePrefetcherTrace,
                "Failed to fetch level = 1, vaddr = 0x%llx\n",
                work_vaddr
            );
            return nullptr;
        }

        // Extract the key value.
        // INT_TYPE is 4 bytes for classes S-C, 8 bytes for classes D-E.
        if (key_buff2_element_size == 4) {
            const Addr offset = \
                (work_vaddr - block_aligned_vaddr) / 4;
            lv1_key_value = \
                (uint64_t)(pkt->getConstPtr<uint32_t>()[offset]);
        } else {
            // element_size == 8 (class D or E)
            const Addr offset = \
                (work_vaddr - block_aligned_vaddr) / 8;
            lv1_key_value = \
                (uint64_t)(pkt->getConstPtr<uint64_t>()[offset]);
        }

        // Add expected prefetch for the key_buff2 cache line itself
        workItem->addExpectedPrefetch(block_aligned_vaddr, 0);
        warnIfOutsideRanges(work_vaddr, block_aligned_vaddr);
        DPRINTF(
            PickleDevicePrefetcherTrace,
            "Work Item = 0x%llx, key_value = %lld\n",
            work_vaddr, lv1_key_value
        );
    }

    // Level 2: prefetch key_buff1[key_value]
    //
    // The core will execute:  key_buff_ptr[key_value]++
    // We compute the virtual address and add it as an expected prefetch.
    {
        const Addr key_buff1_start_vaddr = \
            work_tracker->job_descriptor->get_array(1).vaddr_start;
        const Addr target_vaddr = \
            key_buff1_start_vaddr + lv1_key_value * key_buff1_element_size;
        const Addr target_vaddr_block_aligned = \
            (target_vaddr >> BLOCK_SHIFT) << BLOCK_SHIFT;

        workItem->addExpectedPrefetch(target_vaddr_block_aligned, 1);
        warnIfOutsideRanges(work_vaddr, target_vaddr_block_aligned);
        DPRINTF(
            PickleDevicePrefetcherTrace,
            "Work Item = 0x%llx, key_buff1 prefetch = 0x%llx "
            "(key_value = %lld)\n",
            work_vaddr, target_vaddr_block_aligned, lv1_key_value
        );
    }

    return workItem;
}

} // namespace gem5
