/*
 * Copyright (c) 2026 The Regents of the University of California
 * All rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met: redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer;
 * redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution;
 * neither the name of the copyright holders nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __DMP_PREFETCH_REQUEST_HH__
#define __DMP_PREFETCH_REQUEST_HH__

#include <cstdint>

#include "base/types.hh"
#include "mem/packet.hh"
#include "mem/request.hh"

namespace gem5
{

namespace prefetch
{

namespace dmp
{

// For bookkeeping a prefetch request generated by the DMP prefetcher
class PrefetchRequest
{
  private:
    uint64_t response;
    // Tracking request issue time
    Tick queue_entering_tick;
    Tick start_address_translation_tick;
    Tick end_address_translation_tick;
    Tick memory_request_issued_tick;
    Tick memory_request_complete_tick;
    Tick queue_leaving_tick;
  public:
    // Metadata for this prefetch request
    Addr target_pc;
    Addr prefetch_vaddr;
    uint64_t size;
    uint64_t irt_id;
    bool is_dropped;

    PrefetchRequest(
        const Addr _target_pc, const Addr _prefetch_vaddr,
        const uint64_t _size, const uint64_t _irt_id
    );

    void setResponse(const uint64_t _response);
    bool setResponseFromCacheBlockData(
        const uint8_t* cache_block_data, const uint64_t cache_block_size
    );
    uint64_t getResponse() const;

    void profileQueueEnteringTick();
    void profileStartAddressTranslationTick();
    void profileEndAddressTranslationTick();
    void profileMemoryRequestIssuedTick();
    void profileMemoryRequestCompleteTick();
    void profileQueueLeavingTick();

    Tick getQueueEnteringTick() const;

    Tick getPrefetchLatency() const;
};

} // namespace dmp

} // namespace prefetch

} // namespace gem5

#endif // __DMP_PREFETCH_REQUEST_HH__
