/*
 * Copyright (c) 2026 The Regents of the University of California
 * All rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met: redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer;
 * redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution;
 * neither the name of the copyright holders nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __DMP_PREFETCH_QUEUE_HH__
#define __DMP_PREFETCH_QUEUE_HH__

#include <cstdint>
#include <list>
#include <queue>

#include "arch/generic/mmu.hh"
#include "base/logging.hh"
#include "base/types.hh"
#include "debug/DifferentialMatchingPrefetcherPrefetchQueueDebug.hh"
#include "mem/cache/prefetch/differential_matching_prefetcher/indirect_relation_table.hh"
#include "mem/cache/prefetch/differential_matching_prefetcher/memory_request_manager.hh"
#include "mem/cache/prefetch/differential_matching_prefetcher/prefetch_request.hh"
#include "mem/ruby/slicc_interface/AbstractController.hh"
#include "params/DifferentialMatchingPrefetcherPrefetchQueue.hh"
#include "sim/probe/probe.hh"
#include "sim/system.hh"

#define DMP_PREFETCH_QUEUE_DEBUG(...) \
    DPRINTF(DifferentialMatchingPrefetcherPrefetchQueueDebug,\
            "(Prefetch Queue) " __VA_ARGS__)

namespace gem5
{

namespace prefetch
{

namespace dmp
{

constexpr uint64_t log2(uint64_t n) {
    return (n < 2) ? 0 : 1 + log2(n / 2);
}

/*
 * The backend of a prefetcher, managing prefetch requests generated by the
 * prefetcher.
 */
class PrefetchQueue: public ProbeListenerObject
{
  private:
    System* system;
    ruby::AbstractController *l1_controller;
    const uint64_t queue_size;
    const Addr cache_block_size;
    const Addr block_shift;

    // Regardless of whether we do prefetch address generation in the L1 cache
    // or the L2 cache side, there is always some delay of sending the request
    // from L1 to L2. This delay is modeled here.
    Cycles request_propagation_delay;

    // useful when using traffic generators that already generate physical
    // addresses
    const bool skip_address_translation;

    // Mapping cache block vaddr to prefetch requests
    // According to the DMP paper, each PSHR has a bitmap (per cache block) to
    // track prefetch data to use as index for the next prefetch generation.
    // So, we assume that the PSHR can hold multiple prefetch requests to the
    // same cache block. Hence, we cap the prefetch_requests size by the
    // queue_size.
    std::unordered_map<Addr, std::list<PrefetchRequest>> prefetch_requests;

    MemoryRequestManager memory_request_manager;
    // The Indirect Relation Table (IRT) is shared between the prefetch queue
    // and the differential prefetcher. The prefetch queue needs to access the
    // IRT to generate prefetch addresses based on the matching results from
    // the differential matcher.
    IndirectRelationTable* indirect_relation_table;

  public:
    PARAMS(DifferentialMatchingPrefetcherPrefetchQueue);
    PrefetchQueue(
      const DifferentialMatchingPrefetcherPrefetchQueueParams& params
    );
    void setIndirectRelationTable(IndirectRelationTable* irt);
    bool enqueuePendingRequest(PrefetchRequest prefetch_request);
    bool isFull() const;
    void notifyRequestCompleted(
        const Addr prefetch_vaddr_block_aligned,
        std::vector<uint8_t>& response
    );
};  // class PrefetchQueue

}; // namespace dmp

}; // namespace prefetch

}; // namespace gem5

#endif // __DMP_PREFETCH_QUEUE_HH__
