/*
 * Copyright (c) 2026 The Regents of the University of California
 * All rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met: redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer;
 * redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution;
 * neither the name of the copyright holders nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __DMP_PREFETCH_QUEUE_HH__
#define __DMP_PREFETCH_QUEUE_HH__

#include <cstdint>
#include <deque>
#include <list>
#include <queue>
#include <tuple>
#include <vector>

#include "arch/generic/mmu.hh"
#include "base/logging.hh"
#include "base/statistics.hh"
#include "base/stats/group.hh"
#include "base/types.hh"
#include "cpu/thread_context.hh"
#include "debug/DifferentialMatchingPrefetcherPrefetchQueueDebug.hh"
#include "debug/DifferentialMatchingPrefetcherPrefetchQueueStuckDebug.hh"
#include "enums/PrefetchQueueReplacementPolicy.hh"
#include "mem/cache/prefetch/differential_matching_prefetcher/indirect_relation_table.hh"
#include "mem/cache/prefetch/differential_matching_prefetcher/memory_request_manager.hh"
#include "mem/cache/prefetch/differential_matching_prefetcher/prefetch_request.hh"
#include "mem/cache/prefetch/differential_matching_prefetcher/util.hh"
#include "mem/packet.hh"
#include "mem/ruby/protocol/CHI/Cache_Controller.hh"
#include "mem/ruby/slicc_interface/AbstractController.hh"
#include "params/DifferentialMatchingPrefetcherPrefetchQueue.hh"
#include "sim/clocked_object.hh"
#include "sim/eventq.hh"
#include "sim/probe/probe.hh"
#include "sim/system.hh"

#define DMP_PREFETCH_QUEUE_DEBUG(...) \
    DPRINTF(DifferentialMatchingPrefetcherPrefetchQueueDebug,\
            "(Prefetch Queue) " __VA_ARGS__)
#define DMP_PREFETCH_QUEUE_STUCK_DEBUG(...) \
    DPRINTF(DifferentialMatchingPrefetcherPrefetchQueueStuckDebug,\
            "(Prefetch Queue) " __VA_ARGS__)

namespace gem5
{

namespace prefetch
{

namespace dmp
{

/*
 * The backend of a prefetcher, managing prefetch requests generated by the
 * prefetcher.
 */

class DifferentialMatchingPrefetcher;

class PrefetchQueue : public ClockedObject
{
  private:
    System* system;
    ruby::CHI::Cache_Controller*
      cache_controller; // this is hacky; however, since the local prefetch hit
                     // does not generate a cache hit event, we need to
                     // directly access the L2 controller to get the data
    enums::CacheLevel cache_controller_level;
    DifferentialMatchingPrefetcherInterface* owner;
    const uint64_t queue_size;
    const Addr cache_block_size;
    const Addr block_shift;

    // This event is used to process the new prefetch requests generated after
    // processing the completed prefetch requests.
    EventFunctionWrapper process_pending_new_prefetch_requests_event;

    // This event is used to send stride prefetch results from the L1 prefetch
    // queue to the DMP.
    EventFunctionWrapper
      send_prefetched_data_from_stride_prefetcher_to_dmp_event;

    // The delay of getting data out of the local cache.
    Cycles local_cache_data_access_delay;

    // Regardless of whether we do prefetch address generation in the L1 cache
    // or the L2 cache side, there is always some delay of sending the request
    // from L1 to L2. This delay is modeled here.
    Cycles request_propagation_delay;

    // useful when using traffic generators that already generate physical
    // addresses
    const bool skip_address_translation;

    // Mapping cache block vaddr to prefetch requests
    // According to the DMP paper, each PSHR has a bitmap (per cache block) to
    // track prefetch data to use as index for the next prefetch generation.
    // So, we assume that the PSHR can hold multiple prefetch requests to the
    // same cache block. Hence, we cap the prefetch_requests size by the
    // queue_size.
    std::unordered_map<Addr, std::list<PrefetchRequest>> prefetch_requests;

    MemoryRequestManager memory_request_manager;
    // The Indirect Relation Table (IRT) is shared between the prefetch queue
    // and the differential prefetcher. The prefetch queue needs to access the
    // IRT to generate prefetch addresses based on the matching results from
    // the differential matcher.
    IndirectRelationTable* indirect_relation_table;

    // This queue is used to hold the new prefetch requests generated after
    // processing the completed prefetch requests. These have yet to be
    // coalesced.
    // We use a separate queue to avoid interfering with the ongoing processing
    // of the current prefetch requests in the prefetch_requests map, as the
    // new requests may have addresses that overlap with the current requests,
    // and we don't want to process them together.
    std::deque<PrefetchRequest> pending_new_requests;

    // This queue is used to hold stride prefetch results that are generated
    // in the L1 prefetch queue and need to be sent to the DMP. Since the
    // stride result will generate new prefetch requests in the DMP in the
    // same cycle, and we don't want to interfere with the ongoing processing
    // of the current prefetch requests in the prefetch_requests map, we use a
    // separate queue to hold, we can process them later without affecting the
    // current requests.
    // The tuple contains the vaddr of the prefetched block (this vaddr is only
    // for debugging purposes), the pc of the stride, and the prefetched data.
    std::queue<std::tuple<Addr, Addr, uint64_t>>
      pending_stride_prefetch_results;

    QueuedSet<Addr> recentlyIssuedPrefetches;
  public:
    PARAMS(DifferentialMatchingPrefetcherPrefetchQueue);
    PrefetchQueue(
      const DifferentialMatchingPrefetcherPrefetchQueueParams& params
    );
    void regStats() override;
    void preDumpStats() override;
    void setOwner(DifferentialMatchingPrefetcherInterface* dmp);
    void setCacheController(ruby::AbstractController* cache_controller);
    void setIndirectRelationTable(IndirectRelationTable* irt);
    bool enqueuePendingRequest(PrefetchRequest prefetch_request);
    uint64_t getQueueSize() const;
    bool isFull() const;
    void processPendingNewPrefetchRequests();
    void processPendingStridePrefetchResults();
    void scheduleProcessPendingNewPrefetchRequestsEvent();
    void scheduleProcessPendingStridePrefetchResultsEvent();


    // Memory request interface
    bool hasPendingMemoryRequests() const;
    Tick getNextReadyRequestTick() const;
    PacketPtr getNextRequestPacket();

    // Cache access tracking. The packet is different from the one in the
    // prefetch request as when the prefetch proxy sends the cache access
    // notifications to the prefetcher, the proxy creates a new packet to
    // store the data and the original request. However, we'll need to copy
    // the data out as the packet will be deleted after the notification
    // callback.
    void trackCacheHit(PacketPtr pkt);
    void trackCacheMiss(PacketPtr pkt);
    void trackCacheFill(PacketPtr pkt);

    // Notification interface for memory request completion, called when a
    // prefetch request is completed and the data is sent back to the prefetch
    // queue. These notifications will be forwarded to the MemoryRequestManager
    // for further processing.
    void notifyMemoryRequestCompleted(PacketPtr pkt);

    // Notification interface for processing the completed prefetch requests,
    // called by the MemoryRequestManager when it finishes extracting data
    // from the completed memory requests. The prefetch queue is then
    // responsible for consulting the IRT and generating new prefetch requests.
    void processCompletedPrefetchRequest(
      const Addr prefetch_vaddr_block_aligned,
      const std::vector<uint8_t>& response_data,
      const bool is_prefetch_hit_in_local_cache,
      const bool translation_fault
    );

    // This is for the MemoryRequestManager to tell the prefetcher proxy that
    // the proxy needs to recheck the pending prefetch requests in the prefetch
    // queue as there are still requests need to be scheduled.
    void recheckPendingPrefetchRequests();

  private:
    uint64_t countNumPendingNewRequestsAfterCoalescing() const;

  public:
    struct PrefetchQueueStats : public statistics::Group
    {
        PrefetchQueueStats(statistics::Group* parent);
        void regStats() override;

        statistics::Scalar num_enqueued_requests;
        statistics::Scalar num_requests_after_coalescing;
        statistics::Scalar num_dropped_requests_due_to_full_queue;
        statistics::Scalar num_dropped_requests_due_to_translation_fault;
        statistics::Scalar num_requests_fulfilled_by_local_cache;
        statistics::Scalar num_requests_fulfilled_by_prefetching;

        statistics::Histogram prefetch_queue_occupancy_histogram;
        statistics::Histogram prefetch_request_latency_histogram;

        // Prefetch requests that are stuck in the prefetch queue for a long
        // time may indicate some issues, so we want to track them.
        statistics::Scalar num_prefetch_requests_stuck;
        statistics::Histogram prefetch_request_stuck_duration_histogram;
    } stats;

};  // class PrefetchQueue

}; // namespace dmp

}; // namespace prefetch

}; // namespace gem5

#endif // __DMP_PREFETCH_QUEUE_HH__
